# Generated by Django 4.1.7 on 2026-02-19 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSuggestion',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(max_length=50)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration', models.IntegerField(help_text='Suggested duration in minutes')),
                ('instructions', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workout_suggestions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('total_points', models.IntegerField(default=0)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_points', models.IntegerField(default=0)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('distance', 'Distance'), ('duration', 'Duration'), ('frequency', 'Frequency'), ('points', 'Points')], max_length=50)),
                ('target_value', models.FloatField(help_text='Target value to achieve')),
                ('activity_types', djongo.models.fields.JSONField(blank=True, default=list, help_text='List of applicable activity types')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('points_reward', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('strength_training', 'Strength Training'), ('yoga', 'Yoga'), ('sports', 'Sports'), ('other', 'Other')], max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('distance', models.FloatField(blank=True, help_text='Distance in km', null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-date'],
            },
        ),
    ]
